default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  host: localhost
  port: 5432
  database: aact
  search_path: ctgov,ctgov_api,support

test:
  <<: *default
  database: aact_backend_test
