default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>

  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>

development:
  <<: *default
  host: localhost
  port: 5432
  database: aact
  search_path: ctgov,ctgov_api,support


test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_test


production:
  <<: *default
  url: <%= ENV["DB_URL="] %>
