default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  #TODO: review using fetch
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>

  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_test


production:
  <<: *default
  url: <%= ENV["DB_URL="] %>

external:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("EXTERNAL_DB_POOL") { 5 } %>
  host: <%= ENV.fetch("EXTERNAL_DB_HOST") %>
  port: <%= ENV.fetch("EXTERNAL_DB_PORT") %>
  username: <%= ENV["EXTERNAL_DB_USER"] %>
  password: <%= ENV["EXTERNAL_DB_PASSWORD"] %>
  database: <%= ENV["EXTERNAL_DB_NAME"] %>