default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  host: localhost
  port: 5432
  database: aact
  search_path: ctgov, support

test:
  <<: *default
  database: aact_backend_test

production:
  <<: *default
  database: aact_backend_production
  username: aact_backend
  password: <%= ENV["AACT_BACKEND_DATABASE_PASSWORD"] %>
